version: '3.3'

services:
  server:
    image: back-end-server
    ports:
      - "8089:8089"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/tpachato?useSSL=false
      - spring.datasource.username=$user
      - spring.datasource.password=$password
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE : tpachato
      MYSQL_USER: $user
      MYSQL_PASSWORD: $password
      MYSQL_ROOT_PASSWORD: $root_password
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql

  prometheus:
    image: prom/prometheus:v2.38.0
    network_mode: host
    container_name: prometheus-container
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana-oss:9.1.4
    network_mode: host
    container_name: grafana-container
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/:/var/lib/grafana
  front:
    image : frontangular
    container_name: front
    ports:
      - "4200:4200"
  

  node:
    image: prom/node-exporter
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100

volumes:
    my-db:
